baseurl = "http://gabrielepetri-yoga.de/"
languageCode = "de-de"
title = "Gabriele Petri"
theme = "hyde"

[permalinks]
    post = "/:filename/"


[params]
  themeColor = "theme-base-0b"


[[menu.main]]
        name = "Vijnana Yoga"
        weight = -110
        identifier = "Vijnana"
        url = "/vijnana"
        
[[menu.main]]
        name = "Vita"
        weight = -90
        identifier = "Vita"
        url = "/vita"
        
[[menu.main]]
        name = "Kurse"
        weight = -70
        identifier = "Kurse"
        url = "/kurse"